In [64]:
import pandas as pd
import numpy as np
import unicodedata

# Revisión de los archivos originales en la carpeta crudos
archivos_excel = [
    'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2018.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    'DATOS/Datos crudos/Resultados de la votación 2025.xls'
]

for nombre in archivos_excel:
    temp_df = pd.read_excel(nombre)
    print(f"--- Columnas en {nombre} ---")
    print(temp_df.columns.tolist())
    print("\n")

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2017.xlsx ---
['Cantidad de votos', 'Orden en la votación', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Suma presupuesto proyectos ganadores']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2018.xlsx ---
['Unnamed: 0', 'Olivos - 5 proyectos ganadores', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2019.xlsx ---
['Nº DE PROYECTO EN LA BOLETA DEL BARRIO', 'Cantidad de votos obtenidos por el proyecto', 'Orden en la votación seguún cantidad de votos obtenidos', 'GANADOR', 'BARRIO', 'PROYECTO', 'PRESUPUESTO ESTIMADO', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2021.xlsx ---
['Nro. Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

--- Columnas en DATOS/Datos crudos/Resultados de la votación 2022.xlsx ---
['N° Proyecto en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación según cantidad de votos', 'GANADOR', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Suma presupuestos proyectos ganadores por barrio', 'Disponible para el barrio en 2023']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2023.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2024']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2024.xlsx ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'GANADOR', 'Num barrio', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2025']


--- Columnas en DATOS/Datos crudos/Resultados de la votación 2025.xls ---
['N° Proy en el Barrio', 'Cantidad de votos obtenidos', 'Orden en la votación', 'Ganador', 'Barrio', 'Proyecto', 'Descripción', 'Presupuesto Estimado', 'Observaciones', 'Disponible para el barrio en 2026']

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [65]:
#El archivo de 2018 tenía los datos separados por hoja por barrio. Se recorre cada hoja, se le asigna el nombre del barrio a cada fila y luego las une en una sola tabla para analizar el año completo

archivo_2018 = 'DATOS/Datos crudos/Resultados de la votación 2018.xlsx'

hojas_dict = pd.read_excel(archivo_2018, sheet_name=None, header=1)

lista_de_tablas = []

for nombre_de_la_hoja, tabla_de_la_hoja in hojas_dict.items():
    tabla_de_la_hoja.columns = [str(c).lower().strip() for c in tabla_de_la_hoja.columns]
    
    tabla_de_la_hoja['barrio'] = nombre_de_la_hoja
    
    lista_de_tablas.append(tabla_de_la_hoja)

df_2018_completo = pd.concat(lista_de_tablas, ignore_index=True)

print("Barrios procesados de las hojas:")
print(df_2018_completo['barrio'].unique())

df_2018_completo.head()

Barrios procesados de las hojas:
<StringArray>
[        'Olivos', 'Villa Martelli',  'Florida Oeste',          'Munro',
     'Carapachay',  'Villa Adelina',      'La Lucila',   'Florida Este',
  'Vicente López']
Length: 9, dtype: str

,número de proyecto,descripción,votos válidos,presupuesto estimado del proyecto,observaciones,barrio,votos
0,NaN,NaN,NaN,NaN,PP del barrio: $ 9.833.333,Olivos,NaN
1,9.0,ASOCIACIÓN VECINAL DE FOMENTO Y CULTURA NORTE ...,2753.0,7000000.0,GANADOR,Olivos,NaN
2,27.0,ESCUELAS PRIMARIA Y SECUNDARIA Nº 1: equipamiento,1590.0,2000000.0,GANADOR,Olivos,NaN
3,5.0,ESCUELA PRIMARIA Nº 2: reparaciones varias en ...,1498.0,2000000.0,excede pres. Esc. Provinciales,Olivos,NaN
4,10.0,COLEGIO VIRGEN DEL CARMEN:Cambiar cielorrasos ...,1323.0,438800.0,GANADOR,Olivos,NaN

In [66]:
#Se mapea y limpian los datos de 2018, renombrando columnas originales a nombres comunes con los otros años. 
#Además filtra la info relevante y elimina las filas vacías
dict_hojas = pd.read_excel('DATOS/Datos crudos/Resultados de la votación 2018.xlsx', sheet_name=None, header=1)

lista_final_2018 = []

for nombre_barrio, df_hoja in dict_hojas.items():
    df_hoja.columns = [str(c).lower().strip() for c in df_hoja.columns]
    
    mapeo = {
        'votos válidos': 'votos',
        'descripción': 'proyecto',
        'presupuesto estimado del proyecto': 'presupuesto',
        'observaciones': 'ganador'
    }
    
    df_hoja = df_hoja.rename(columns=mapeo)
    
    df_hoja['barrio'] = nombre_barrio
    df_hoja['año'] = 2018
    
    cols_interes = ['votos', 'barrio', 'proyecto', 'presupuesto', 'ganador', 'año']
    df_hoja = df_hoja[[c for c in cols_interes if c in df_hoja.columns]]
    
    lista_final_2018.append(df_hoja)

df_2018_final = pd.concat(lista_final_2018, ignore_index=True)

df_2018_final = df_2018_final.dropna(subset=['votos', 'proyecto'], how='all')

print("Ahora todos los barrios están unificados.")
df_2018_final.sample(10)

Ahora todos los barrios están unificados.

,votos,barrio,proyecto,presupuesto,ganador,año
3,1498.0,Olivos,ESCUELA PRIMARIA Nº 2: reparaciones varias en ...,2000000.0,excede pres. Esc. Provinciales,2018
6,1048.0,Olivos,CRUZ ROJA: puesto móvil de gestión de emergenc...,900000.0,excede presupuesto,2018
25,291.0,Olivos,CESTOS PAPELEROS EN EL BARRIO,486000.0,excede presupuesto,2018
119,82.0,Munro,LA ECOLOGIA COMIENZA POR CASA: talleres teatra...,320000.0,NaN,2018
151,276.0,La Lucila,Jardín de Infantes Municipal N° 8: sistema de ...,579685.0,GANADOR,2018
51,229.0,Villa Martelli,"ESCUELA PRIMARIA Nº 11: Reparar piso de aula, ...",1092000.0,excede presupuesto,2018
47,286.0,Villa Martelli,FUNDACIÓN CAMINO: Instalación electrica,1000000.0,excede presupuesto,2018
162,2028.0,Florida Este,Club Social y Deportivo Caseros: puesta en val...,3000000.0,PROYECTO GANADOR,2018
96,454.0,Munro,CONTENEDORES DE RESIDUOS EN CENTRO COMERCIAL D...,285500.0,excede presupuesto,2018
75,184.0,Florida Oeste,RAMPAS EN EL BARRIO (varias ubicaciones),975000.0,excede presupuesto,2018

In [67]:

#Se clasifican en temáticas los proyectos de acuerdo a palabras clave que identifican cada uno
MAPEO_PROYECTOS = {
    'Salud': ['cruz roja', 'salud', 'hospital', 'unidad de respuesta', 'salita', 'maternal', 'ambulatoria', 'vacunatorio', 'medico', 'ambulancia', 'emergencia', 'emergencias', 'droga', 'sangre', 'anestesia', 'clinico', 'zoonosis', 'caps', 'pacientes', 'uap', 'uri', 'enfermería', 'apovilo', 'hospice', 'lalcec', 'rcp', 'primeros auxilios', 'cires', 'kinefilaxis', 'rehabilitación'],
    'Cultura': ['malvinas','percusión','libro', 'veteranos', 'cultura', 'teatro', 'museo', 'centro cultural', 'biblioteca', 'talleres', 'musica', 'danza', 'orquesta', 'turismo', 'cine', 'arte', 'instrumento', 'histórica', 'historia', 'archivo', 'torre ader', 'mural', 'memoria', 'coro', 'audiovisual'],
    'Educación': ['escuela', 'jardin', 'colegio', 'secundaria', 'primaria', 'estudiantil', 'educacion', 'lectura', 'aula', 'pizarron', 'escuelita', 'educativo', 'docente', 'instituto', 'infantil', 'formacion', 'capacitación'],
    'Seguridad': ['bombero', 'voluntario', 'camara', 'seguridad', 'patrullero', 'iluminacion', 'luces', 'alarma', 'totem', 'vigilancia', 'punto seguro', 'monitoreo', 'vallas', 'contención'],
    'Movilidad': ['semaforo','demarcación','circulación', 'señalizacion', 'transporte', 'bicisenda', 'ciclovia', 'parada de colectivo', 'refugio', 'transito', 'estacionamiento', 'reductores', 'reducidores', 'carteles', 'carteleria', 'sendas peatonales', 'sendas', 'velocidad', 'peatonales', 'vial', 'senal', 'metrobus', 'bacheo', 'asfalto', 'pavimento', 'accesibles', 'accesibilidad', 'dársena', 'circulación','estación'],
    'Medio Ambiente': ['reciclaje', 'fauna','animal', 'ecologia', 'ecosistema', 'arbolar', 'arbolado', 'ecologica', 'arboles', 'huerta', 'puntos verdes', 'sustentable', 'compost', 'separacion de residuos', 'ecologico', 'punto verde', 'plantado', 'cesto', 'cestos', 'reciclado', 'basura', 'tierra', 'contenedor', 'ambiental', 'botella', 'bolsa', 'poda', 'aves', 'especies','plantación','reforestación'],
    'Deporte': ['deporte', 'club','tribuna', 'gimnasio', 'playon', 'cancha', 'polideportivo', 'entrenamiento', 'futbol', 'natatorio', 'rugby', 'bmx', 'aeróbicas', 'barras', 'calistenia'],
    'Espacio Público': ['plaza', 'parque', 'canil', 'vereda', 'espacio publico', 'espacios publicos', 'plazoleta', 'limpio', 'bebederos', 'caniles', 'banco', 'parquizado', 'paseo', 'costa', 'mobiliario'],
    'Reparaciones/Obra': ['pintura', 'rampa', 'rampas', 'construccion', 'reconstruccion', 'instalacion', 'remodelacion', 'mejoramiento edilicio', 'refaccion', 'obra', 'obras', 'ampliacion', 'cambio', 'luminarias', 'edilicias', 'edilicia', 'techo', 'reparacion', 'iluminando', 'impermeabilizacion', 'baño', 'gas', 'electricidad', 'alero', 'galería', 'piso'],
    'Social': ['tercera edad', 'juventud','capacitación', 'adultos mayores', 'genero', 'discapacidad', 'integracion', 'comedor', 'merendero', 'social', 'jubilados', 'scout', 'centro comunitario', 'sociedad', 'fomento', 'hogar', 'asociacion', 'fundacion', 'circulo', 'union', 'recreativo', 'lactancia', 'iglesia', 'parroquia', 'virgen', 'capilla', 'voluntariado', 'voluntarias', 'caritas','jubilado']
}

def clasificador_final(titulo):
    if pd.isna(titulo): return "Otros/Varios"
    
    # Limpieza estándar
    t = str(titulo).lower()
    t = ''.join(c for c in unicodedata.normalize('NFD', t) if unicodedata.category(c) != 'Mn')
    
    # El bucle recorre el diccionario. 
    for categoria, palabras in MAPEO_PROYECTOS.items():
        if any(p in t for p in palabras):
            return categoria
            
    return "Otros/Varios"

In [68]:
#Se procesan los años estandarizando los nombres de las columnas y chequear que todos los archivos se carguen sin errores de compatibilidad
archivos_otros_años = {
    2017: 'DATOS/Datos crudos/Resultados de la votación 2017.xlsx',
    2019: 'DATOS/Datos crudos/Resultados de la votación 2019.xlsx',
    2021: 'DATOS/Datos crudos/Resultados de la votación 2021.xlsx',
    2022: 'DATOS/Datos crudos/Resultados de la votación 2022.xlsx',
    2023: 'DATOS/Datos crudos/Resultados de la votación 2023.xlsx',
    2024: 'DATOS/Datos crudos/Resultados de la votación 2024.xlsx',
    2025: 'DATOS/Datos crudos/Resultados de la votación 2025.xls'
}

lista_dfs = []
for año, archivo in archivos_otros_años.items():
    engine = 'xlrd' if archivo.endswith('.xls') else 'openpyxl'
    
    df_temp = pd.read_excel(archivo, engine=engine)
    
    df_temp.columns = [str(c).lower().strip() for c in df_temp.columns]
    
    mapeo = {
        'cantidad de votos obtenidos': 'votos', 
        'cantidad de votos': 'votos', 
        'presupuesto estimado': 'presupuesto', 
        'ganador': 'ganador', 
        'barrio': 'barrio', 
        'proyecto': 'proyecto'
    }
    
    df_temp = df_temp.rename(columns=mapeo)
    df_temp['año'] = año
    lista_dfs.append(df_temp)

c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\cerru\OneDrive\Documentos\TP FINAL DATOS\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [69]:
#Carga del archivo histórico de proyectos ganadores
archivo_historico= 'DATOS/Datos crudos/Históricos Presupuesto.xlsx'
df_historico=pd.read_excel(archivo_historico)

#Se filtran sólo los años entre 2013 y 2016
df_historico=df_historico[df_historico['Año'].isin([2013,2014,2015,2016])].copy()

#Renombramos columnas
mapeo_historico={
    'Año':'año',
    'Barrio':'barrio',
    'Título Proyecto':'proyecto',
    'Presupuesto invertido':'presupuesto',
    'Cantidad de votos válidos obtenidos':'votos'
}
df_historico=df_historico.rename(columns=mapeo_historico)

#Se aplica la función de categorías que se definió
df_historico['categoria']=df_historico['proyecto'].apply(clasificador_final)

#Se asigna 1 a todos los proyectos porque son todos los ganadores
df_historico['ganador_bin']=1

#Seleccionamos las columnas finales
columnas_finales=['año','barrio','proyecto','categoria','votos','presupuesto','ganador_bin']
df_historico_final=df_historico[columnas_finales]

#Agregamos a nuestra lista para que se una
lista_dfs.append(df_historico_final)

print("2013-2016 integrados")

2013-2016 integrados

In [70]:
#Confirmamos que todos los años se procesaron bien
anios = [str(df['año'].unique()[0]) for df in lista_dfs]
print(f"Años cargados en la lista: {', '.join(anios)}")

Años cargados en la lista: 2017, 2019, 2021, 2022, 2023, 2024, 2025, 2016

In [71]:
# Se unifica la lista de todos los años
vilo_master = pd.concat(lista_dfs + [df_2018_final], ignore_index=True)

# CORRECCIÓN: Cambiamos 'categorizar_proyecto' por 'clasificador_final' 
# (que es el nombre que definiste en tu diccionario en el Bloque 4)
vilo_master['categoria'] = vilo_master['proyecto'].apply(clasificador_final)

# Además se crea una columna para saber si el proyecto ganó o no
vilo_master['ganador_bin'] = vilo_master['ganador'].apply(lambda x: 1 if str(x).strip().upper() in ['SI', 'GANADOR'] else 0)

# Se guarda el resultado final
vilo_master.to_csv('DATOS/Datos procesados/dataset_final_vilo.csv', index=False, encoding='utf-8-sig')
print("¡Todo unificado con éxito!")

¡Todo unificado con éxito!

In [72]:
#Muestra la lista final de columnas para asegurar que el mapeo funcionó
print(vilo_master.columns.tolist())

['votos', 'orden en la votación', 'ganador', 'barrio', 'proyecto', 'presupuesto', 'suma presupuesto proyectos ganadores', 'año', 'nº de proyecto en la boleta del barrio', 'cantidad de votos obtenidos por el proyecto', 'orden en la votación seguún cantidad de votos obtenidos', 'observaciones', 'suma presupuestos proyectos ganadores por barrio', 'nro. proyecto en el barrio', 'orden en la votación según cantidad de votos', 'descripción', 'n° proyecto en el barrio', 'disponible para el barrio en 2023', 'n° proy en el barrio', 'num barrio', 'disponible para el barrio en 2024', 'disponible para el barrio en 2025', 'disponible para el barrio en 2026', 'categoria', 'ganador_bin']

In [73]:
#Hacemos la copia
df_limpio = vilo_master.copy()

#Unificamos columnas de votos
columnas_votos = ['cantidad de votos obtenidos por el proyecto', 'cantidad de votos obtenidos']
for col in columnas_votos:
    if col in df_limpio.columns:
        df_limpio['votos'] = df_limpio['votos'].fillna(df_limpio[col])

#Unificamos descripción
if 'descripción' in df_limpio.columns:
    df_limpio['proyecto'] = df_limpio['proyecto'].fillna(df_limpio['descripción'])

#Rescatamos ganadores de observaciones
if 'observaciones' in df_limpio.columns:
    mask = df_limpio['observaciones'].str.contains('GANADOR', na=False, case=False)
    df_limpio.loc[mask, 'ganador_bin'] = 1

#Selección de columnas finales
columnas_finales = [
    'año', 
    'barrio', 
    'proyecto', 
    'categoria', 
    'votos', 
    'presupuesto', 
    'ganador_bin'
]
dataset_tif = df_limpio[columnas_finales].copy()

#Limpieza de filas y conversión a ENTEROS (int)
dataset_tif = dataset_tif.dropna(subset=['proyecto', 'barrio'])

dataset_tif['votos'] = pd.to_numeric(dataset_tif['votos'], errors='coerce').fillna(0).astype(int)
dataset_tif['presupuesto'] = pd.to_numeric(dataset_tif['presupuesto'], errors='coerce').fillna(0).astype(int)

# CORRECCIÓN DE RUTAS:
ruta_salida = 'DATOS/Datos procesados/dataset_final_vilo.csv'

dataset_tif.to_csv(ruta_salida, index=False, sep=';', encoding='utf-8-sig')

print("Dataset pulido y guardado")
print(f"Total de registros: {len(dataset_tif)}")
dataset_tif.head()

Dataset pulido y guardado
Total de registros: 1726

,año,barrio,proyecto,categoria,votos,presupuesto,ganador_bin
0,2017,Villa Martelli,BOMBEROS VOLUNTARIOS DE VICENTE LÓPEZ - 25 equ...,Seguridad,959,978500,1
1,2017,Villa Martelli,CAMPAÑA DE CONCIENTIZACIÓN SOBRE EL BULLYING -...,Cultura,506,193892,1
2,2017,Villa Martelli,FUNDACION CAMINO - Remodelación interior y fac...,Reparaciones/Obra,487,1500000,1
3,2017,Villa Martelli,ESCUELA SECUNDARIA Nº 2 (provincial) - Reparac...,Educación,482,1200000,1
4,2017,Villa Martelli,BIBLIOTECA FROILÁN GONZÁLEZ - Compra de mobili...,Cultura,446,132000,1

In [74]:
print(dataset_tif['categoria'].value_counts())

categoria
Educación            382
Social               243
Movilidad            176
Cultura              166
Salud                159
Deporte              149
Seguridad            121
Medio Ambiente       110
Reparaciones/Obra     78
Espacio Público       78
Otros/Varios          64
Name: count, dtype: int64